### ISSUE TITLE
Doesn't work with Bootstrap

### ISSUE THREAD

**Issue by pavlosherin** [boatzako/ng2-simple-smooth-scroll#3]
There is an issue that doesn't allow scroll to element wrapped in element which has css property `position: relative`.
Unfortunately it's basic usage of Bootstrap grid (rows and columns), columns have css property position relative.
See the demo (https://angular6-smooth-scroll-demo-6z8rmb.stackblitz.io)
Any idea how to solve it?

**Comment by boatzako** [comment]
Fixed in @boatzako/ngx-smooth-scroll@2.1.0
https://angular6-smooth-scroll-demo-jv3wsa.stackblitz.io/

**Comment by boatzako** [comment]
Fixed in @boatzako/ngx-smooth-scroll@2.1.0
https://angular6-smooth-scroll-demo-jv3wsa.stackblitz.io/
